/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsTelemetryExportConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsTelemetryExportConfig{}

// CommonsTelemetryExportConfig struct for CommonsTelemetryExportConfig
type CommonsTelemetryExportConfig struct {
	Endpoint             *string            `json:"endpoint,omitempty"`
	Headers              *map[string]string `json:"headers,omitempty"`
	ResourceAttrs        *map[string]string `json:"resource_attrs,omitempty"`
	Signals              []string           `json:"signals,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsTelemetryExportConfig CommonsTelemetryExportConfig

// NewCommonsTelemetryExportConfig instantiates a new CommonsTelemetryExportConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsTelemetryExportConfig() *CommonsTelemetryExportConfig {
	this := CommonsTelemetryExportConfig{}
	return &this
}

// NewCommonsTelemetryExportConfigWithDefaults instantiates a new CommonsTelemetryExportConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsTelemetryExportConfigWithDefaults() *CommonsTelemetryExportConfig {
	this := CommonsTelemetryExportConfig{}
	return &this
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *CommonsTelemetryExportConfig) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsTelemetryExportConfig) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *CommonsTelemetryExportConfig) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *CommonsTelemetryExportConfig) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *CommonsTelemetryExportConfig) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsTelemetryExportConfig) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *CommonsTelemetryExportConfig) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *CommonsTelemetryExportConfig) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetResourceAttrs returns the ResourceAttrs field value if set, zero value otherwise.
func (o *CommonsTelemetryExportConfig) GetResourceAttrs() map[string]string {
	if o == nil || IsNil(o.ResourceAttrs) {
		var ret map[string]string
		return ret
	}
	return *o.ResourceAttrs
}

// GetResourceAttrsOk returns a tuple with the ResourceAttrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsTelemetryExportConfig) GetResourceAttrsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ResourceAttrs) {
		return nil, false
	}
	return o.ResourceAttrs, true
}

// HasResourceAttrs returns a boolean if a field has been set.
func (o *CommonsTelemetryExportConfig) HasResourceAttrs() bool {
	if o != nil && !IsNil(o.ResourceAttrs) {
		return true
	}

	return false
}

// SetResourceAttrs gets a reference to the given map[string]string and assigns it to the ResourceAttrs field.
func (o *CommonsTelemetryExportConfig) SetResourceAttrs(v map[string]string) {
	o.ResourceAttrs = &v
}

// GetSignals returns the Signals field value if set, zero value otherwise.
func (o *CommonsTelemetryExportConfig) GetSignals() []string {
	if o == nil || IsNil(o.Signals) {
		var ret []string
		return ret
	}
	return o.Signals
}

// GetSignalsOk returns a tuple with the Signals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsTelemetryExportConfig) GetSignalsOk() ([]string, bool) {
	if o == nil || IsNil(o.Signals) {
		return nil, false
	}
	return o.Signals, true
}

// HasSignals returns a boolean if a field has been set.
func (o *CommonsTelemetryExportConfig) HasSignals() bool {
	if o != nil && !IsNil(o.Signals) {
		return true
	}

	return false
}

// SetSignals gets a reference to the given []string and assigns it to the Signals field.
func (o *CommonsTelemetryExportConfig) SetSignals(v []string) {
	o.Signals = v
}

func (o CommonsTelemetryExportConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsTelemetryExportConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.ResourceAttrs) {
		toSerialize["resource_attrs"] = o.ResourceAttrs
	}
	if !IsNil(o.Signals) {
		toSerialize["signals"] = o.Signals
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsTelemetryExportConfig) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsTelemetryExportConfig := _CommonsTelemetryExportConfig{}

	err = json.Unmarshal(bytes, &varCommonsTelemetryExportConfig)

	if err != nil {
		return err
	}

	*o = CommonsTelemetryExportConfig(varCommonsTelemetryExportConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "endpoint")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "resource_attrs")
		delete(additionalProperties, "signals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsTelemetryExportConfig struct {
	value *CommonsTelemetryExportConfig
	isSet bool
}

func (v NullableCommonsTelemetryExportConfig) Get() *CommonsTelemetryExportConfig {
	return v.value
}

func (v *NullableCommonsTelemetryExportConfig) Set(val *CommonsTelemetryExportConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsTelemetryExportConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsTelemetryExportConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsTelemetryExportConfig(val *CommonsTelemetryExportConfig) *NullableCommonsTelemetryExportConfig {
	return &NullableCommonsTelemetryExportConfig{value: val, isSet: true}
}

func (v NullableCommonsTelemetryExportConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsTelemetryExportConfig) UnmarshalJSON(src []byte) (err error) {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
