/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the WarpWorkflowsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarpWorkflowsRequest{}

// WarpWorkflowsRequest struct for WarpWorkflowsRequest
type WarpWorkflowsRequest struct {
	// for github oauth flow
	Authorization *map[string]string `json:"authorization,omitempty"`
	RunnerId string `json:"runner_id"`
	WorkflowIds []string `json:"workflow_ids"`
	AdditionalProperties map[string]interface{}
}

type _WarpWorkflowsRequest WarpWorkflowsRequest

// NewWarpWorkflowsRequest instantiates a new WarpWorkflowsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarpWorkflowsRequest(runnerId string, workflowIds []string) *WarpWorkflowsRequest {
	this := WarpWorkflowsRequest{}
	this.RunnerId = runnerId
	this.WorkflowIds = workflowIds
	return &this
}

// NewWarpWorkflowsRequestWithDefaults instantiates a new WarpWorkflowsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarpWorkflowsRequestWithDefaults() *WarpWorkflowsRequest {
	this := WarpWorkflowsRequest{}
	return &this
}

// GetAuthorization returns the Authorization field value if set, zero value otherwise.
func (o *WarpWorkflowsRequest) GetAuthorization() map[string]string {
	if o == nil || IsNil(o.Authorization) {
		var ret map[string]string
		return ret
	}
	return *o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WarpWorkflowsRequest) GetAuthorizationOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Authorization) {
		return nil, false
	}
	return o.Authorization, true
}

// HasAuthorization returns a boolean if a field has been set.
func (o *WarpWorkflowsRequest) HasAuthorization() bool {
	if o != nil && !IsNil(o.Authorization) {
		return true
	}

	return false
}

// SetAuthorization gets a reference to the given map[string]string and assigns it to the Authorization field.
func (o *WarpWorkflowsRequest) SetAuthorization(v map[string]string) {
	o.Authorization = &v
}

// GetRunnerId returns the RunnerId field value
func (o *WarpWorkflowsRequest) GetRunnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunnerId
}

// GetRunnerIdOk returns a tuple with the RunnerId field value
// and a boolean to check if the value has been set.
func (o *WarpWorkflowsRequest) GetRunnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunnerId, true
}

// SetRunnerId sets field value
func (o *WarpWorkflowsRequest) SetRunnerId(v string) {
	o.RunnerId = v
}

// GetWorkflowIds returns the WorkflowIds field value
func (o *WarpWorkflowsRequest) GetWorkflowIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WorkflowIds
}

// GetWorkflowIdsOk returns a tuple with the WorkflowIds field value
// and a boolean to check if the value has been set.
func (o *WarpWorkflowsRequest) GetWorkflowIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowIds, true
}

// SetWorkflowIds sets field value
func (o *WarpWorkflowsRequest) SetWorkflowIds(v []string) {
	o.WorkflowIds = v
}

func (o WarpWorkflowsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarpWorkflowsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authorization) {
		toSerialize["authorization"] = o.Authorization
	}
	toSerialize["runner_id"] = o.RunnerId
	toSerialize["workflow_ids"] = o.WorkflowIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WarpWorkflowsRequest) UnmarshalJSON(bytes []byte) (err error) {
	varWarpWorkflowsRequest := _WarpWorkflowsRequest{}

	if err = json.Unmarshal(bytes, &varWarpWorkflowsRequest); err == nil {
		*o = WarpWorkflowsRequest(varWarpWorkflowsRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "authorization")
		delete(additionalProperties, "runner_id")
		delete(additionalProperties, "workflow_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWarpWorkflowsRequest struct {
	value *WarpWorkflowsRequest
	isSet bool
}

func (v NullableWarpWorkflowsRequest) Get() *WarpWorkflowsRequest {
	return v.value
}

func (v *NullableWarpWorkflowsRequest) Set(val *WarpWorkflowsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWarpWorkflowsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWarpWorkflowsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarpWorkflowsRequest(val *WarpWorkflowsRequest) *NullableWarpWorkflowsRequest {
	return &NullableWarpWorkflowsRequest{value: val, isSet: true}
}

func (v NullableWarpWorkflowsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarpWorkflowsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


