/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsRunnerSetDefaultGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsRunnerSetDefaultGroup{}

// CommonsRunnerSetDefaultGroup struct for CommonsRunnerSetDefaultGroup
type CommonsRunnerSetDefaultGroup struct {
	GroupId *int32 `json:"group_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsRunnerSetDefaultGroup CommonsRunnerSetDefaultGroup

// NewCommonsRunnerSetDefaultGroup instantiates a new CommonsRunnerSetDefaultGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsRunnerSetDefaultGroup() *CommonsRunnerSetDefaultGroup {
	this := CommonsRunnerSetDefaultGroup{}
	return &this
}

// NewCommonsRunnerSetDefaultGroupWithDefaults instantiates a new CommonsRunnerSetDefaultGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsRunnerSetDefaultGroupWithDefaults() *CommonsRunnerSetDefaultGroup {
	this := CommonsRunnerSetDefaultGroup{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *CommonsRunnerSetDefaultGroup) GetGroupId() int32 {
	if o == nil || IsNil(o.GroupId) {
		var ret int32
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerSetDefaultGroup) GetGroupIdOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *CommonsRunnerSetDefaultGroup) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int32 and assigns it to the GroupId field.
func (o *CommonsRunnerSetDefaultGroup) SetGroupId(v int32) {
	o.GroupId = &v
}

func (o CommonsRunnerSetDefaultGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsRunnerSetDefaultGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsRunnerSetDefaultGroup) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsRunnerSetDefaultGroup := _CommonsRunnerSetDefaultGroup{}

	if err = json.Unmarshal(bytes, &varCommonsRunnerSetDefaultGroup); err == nil {
		*o = CommonsRunnerSetDefaultGroup(varCommonsRunnerSetDefaultGroup)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "group_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsRunnerSetDefaultGroup struct {
	value *CommonsRunnerSetDefaultGroup
	isSet bool
}

func (v NullableCommonsRunnerSetDefaultGroup) Get() *CommonsRunnerSetDefaultGroup {
	return v.value
}

func (v *NullableCommonsRunnerSetDefaultGroup) Set(val *CommonsRunnerSetDefaultGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsRunnerSetDefaultGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsRunnerSetDefaultGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsRunnerSetDefaultGroup(val *CommonsRunnerSetDefaultGroup) *NullableCommonsRunnerSetDefaultGroup {
	return &NullableCommonsRunnerSetDefaultGroup{value: val, isSet: true}
}

func (v NullableCommonsRunnerSetDefaultGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsRunnerSetDefaultGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


