/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsLastJobProcessedMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsLastJobProcessedMeta{}

// CommonsLastJobProcessedMeta struct for CommonsLastJobProcessedMeta
type CommonsLastJobProcessedMeta struct {
	VcsBaseRef *string `json:"vcs_base_ref,omitempty"`
	VcsCommitMessage *string `json:"vcs_commit_message,omitempty"`
	VcsDefaultBranch *string `json:"vcs_default_branch,omitempty"`
	VcsEndTime *string `json:"vcs_end_time,omitempty"`
	VcsHeadRef *string `json:"vcs_head_ref,omitempty"`
	VcsJobName *string `json:"vcs_job_name,omitempty"`
	VcsOrg *string `json:"vcs_org,omitempty"`
	VcsRef *string `json:"vcs_ref,omitempty"`
	VcsRefType *string `json:"vcs_ref_type,omitempty"`
	VcsRepo *string `json:"vcs_repo,omitempty"`
	VcsStartTime *string `json:"vcs_start_time,omitempty"`
	VcsWorkflowGroupId *string `json:"vcs_workflow_group_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsLastJobProcessedMeta CommonsLastJobProcessedMeta

// NewCommonsLastJobProcessedMeta instantiates a new CommonsLastJobProcessedMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsLastJobProcessedMeta() *CommonsLastJobProcessedMeta {
	this := CommonsLastJobProcessedMeta{}
	return &this
}

// NewCommonsLastJobProcessedMetaWithDefaults instantiates a new CommonsLastJobProcessedMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsLastJobProcessedMetaWithDefaults() *CommonsLastJobProcessedMeta {
	this := CommonsLastJobProcessedMeta{}
	return &this
}

// GetVcsBaseRef returns the VcsBaseRef field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsBaseRef() string {
	if o == nil || IsNil(o.VcsBaseRef) {
		var ret string
		return ret
	}
	return *o.VcsBaseRef
}

// GetVcsBaseRefOk returns a tuple with the VcsBaseRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsBaseRefOk() (*string, bool) {
	if o == nil || IsNil(o.VcsBaseRef) {
		return nil, false
	}
	return o.VcsBaseRef, true
}

// HasVcsBaseRef returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsBaseRef() bool {
	if o != nil && !IsNil(o.VcsBaseRef) {
		return true
	}

	return false
}

// SetVcsBaseRef gets a reference to the given string and assigns it to the VcsBaseRef field.
func (o *CommonsLastJobProcessedMeta) SetVcsBaseRef(v string) {
	o.VcsBaseRef = &v
}

// GetVcsCommitMessage returns the VcsCommitMessage field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsCommitMessage() string {
	if o == nil || IsNil(o.VcsCommitMessage) {
		var ret string
		return ret
	}
	return *o.VcsCommitMessage
}

// GetVcsCommitMessageOk returns a tuple with the VcsCommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsCommitMessageOk() (*string, bool) {
	if o == nil || IsNil(o.VcsCommitMessage) {
		return nil, false
	}
	return o.VcsCommitMessage, true
}

// HasVcsCommitMessage returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsCommitMessage() bool {
	if o != nil && !IsNil(o.VcsCommitMessage) {
		return true
	}

	return false
}

// SetVcsCommitMessage gets a reference to the given string and assigns it to the VcsCommitMessage field.
func (o *CommonsLastJobProcessedMeta) SetVcsCommitMessage(v string) {
	o.VcsCommitMessage = &v
}

// GetVcsDefaultBranch returns the VcsDefaultBranch field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsDefaultBranch() string {
	if o == nil || IsNil(o.VcsDefaultBranch) {
		var ret string
		return ret
	}
	return *o.VcsDefaultBranch
}

// GetVcsDefaultBranchOk returns a tuple with the VcsDefaultBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsDefaultBranchOk() (*string, bool) {
	if o == nil || IsNil(o.VcsDefaultBranch) {
		return nil, false
	}
	return o.VcsDefaultBranch, true
}

// HasVcsDefaultBranch returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsDefaultBranch() bool {
	if o != nil && !IsNil(o.VcsDefaultBranch) {
		return true
	}

	return false
}

// SetVcsDefaultBranch gets a reference to the given string and assigns it to the VcsDefaultBranch field.
func (o *CommonsLastJobProcessedMeta) SetVcsDefaultBranch(v string) {
	o.VcsDefaultBranch = &v
}

// GetVcsEndTime returns the VcsEndTime field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsEndTime() string {
	if o == nil || IsNil(o.VcsEndTime) {
		var ret string
		return ret
	}
	return *o.VcsEndTime
}

// GetVcsEndTimeOk returns a tuple with the VcsEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.VcsEndTime) {
		return nil, false
	}
	return o.VcsEndTime, true
}

// HasVcsEndTime returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsEndTime() bool {
	if o != nil && !IsNil(o.VcsEndTime) {
		return true
	}

	return false
}

// SetVcsEndTime gets a reference to the given string and assigns it to the VcsEndTime field.
func (o *CommonsLastJobProcessedMeta) SetVcsEndTime(v string) {
	o.VcsEndTime = &v
}

// GetVcsHeadRef returns the VcsHeadRef field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsHeadRef() string {
	if o == nil || IsNil(o.VcsHeadRef) {
		var ret string
		return ret
	}
	return *o.VcsHeadRef
}

// GetVcsHeadRefOk returns a tuple with the VcsHeadRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsHeadRefOk() (*string, bool) {
	if o == nil || IsNil(o.VcsHeadRef) {
		return nil, false
	}
	return o.VcsHeadRef, true
}

// HasVcsHeadRef returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsHeadRef() bool {
	if o != nil && !IsNil(o.VcsHeadRef) {
		return true
	}

	return false
}

// SetVcsHeadRef gets a reference to the given string and assigns it to the VcsHeadRef field.
func (o *CommonsLastJobProcessedMeta) SetVcsHeadRef(v string) {
	o.VcsHeadRef = &v
}

// GetVcsJobName returns the VcsJobName field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsJobName() string {
	if o == nil || IsNil(o.VcsJobName) {
		var ret string
		return ret
	}
	return *o.VcsJobName
}

// GetVcsJobNameOk returns a tuple with the VcsJobName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsJobNameOk() (*string, bool) {
	if o == nil || IsNil(o.VcsJobName) {
		return nil, false
	}
	return o.VcsJobName, true
}

// HasVcsJobName returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsJobName() bool {
	if o != nil && !IsNil(o.VcsJobName) {
		return true
	}

	return false
}

// SetVcsJobName gets a reference to the given string and assigns it to the VcsJobName field.
func (o *CommonsLastJobProcessedMeta) SetVcsJobName(v string) {
	o.VcsJobName = &v
}

// GetVcsOrg returns the VcsOrg field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsOrg() string {
	if o == nil || IsNil(o.VcsOrg) {
		var ret string
		return ret
	}
	return *o.VcsOrg
}

// GetVcsOrgOk returns a tuple with the VcsOrg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsOrgOk() (*string, bool) {
	if o == nil || IsNil(o.VcsOrg) {
		return nil, false
	}
	return o.VcsOrg, true
}

// HasVcsOrg returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsOrg() bool {
	if o != nil && !IsNil(o.VcsOrg) {
		return true
	}

	return false
}

// SetVcsOrg gets a reference to the given string and assigns it to the VcsOrg field.
func (o *CommonsLastJobProcessedMeta) SetVcsOrg(v string) {
	o.VcsOrg = &v
}

// GetVcsRef returns the VcsRef field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsRef() string {
	if o == nil || IsNil(o.VcsRef) {
		var ret string
		return ret
	}
	return *o.VcsRef
}

// GetVcsRefOk returns a tuple with the VcsRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsRefOk() (*string, bool) {
	if o == nil || IsNil(o.VcsRef) {
		return nil, false
	}
	return o.VcsRef, true
}

// HasVcsRef returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsRef() bool {
	if o != nil && !IsNil(o.VcsRef) {
		return true
	}

	return false
}

// SetVcsRef gets a reference to the given string and assigns it to the VcsRef field.
func (o *CommonsLastJobProcessedMeta) SetVcsRef(v string) {
	o.VcsRef = &v
}

// GetVcsRefType returns the VcsRefType field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsRefType() string {
	if o == nil || IsNil(o.VcsRefType) {
		var ret string
		return ret
	}
	return *o.VcsRefType
}

// GetVcsRefTypeOk returns a tuple with the VcsRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VcsRefType) {
		return nil, false
	}
	return o.VcsRefType, true
}

// HasVcsRefType returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsRefType() bool {
	if o != nil && !IsNil(o.VcsRefType) {
		return true
	}

	return false
}

// SetVcsRefType gets a reference to the given string and assigns it to the VcsRefType field.
func (o *CommonsLastJobProcessedMeta) SetVcsRefType(v string) {
	o.VcsRefType = &v
}

// GetVcsRepo returns the VcsRepo field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsRepo() string {
	if o == nil || IsNil(o.VcsRepo) {
		var ret string
		return ret
	}
	return *o.VcsRepo
}

// GetVcsRepoOk returns a tuple with the VcsRepo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsRepoOk() (*string, bool) {
	if o == nil || IsNil(o.VcsRepo) {
		return nil, false
	}
	return o.VcsRepo, true
}

// HasVcsRepo returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsRepo() bool {
	if o != nil && !IsNil(o.VcsRepo) {
		return true
	}

	return false
}

// SetVcsRepo gets a reference to the given string and assigns it to the VcsRepo field.
func (o *CommonsLastJobProcessedMeta) SetVcsRepo(v string) {
	o.VcsRepo = &v
}

// GetVcsStartTime returns the VcsStartTime field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsStartTime() string {
	if o == nil || IsNil(o.VcsStartTime) {
		var ret string
		return ret
	}
	return *o.VcsStartTime
}

// GetVcsStartTimeOk returns a tuple with the VcsStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.VcsStartTime) {
		return nil, false
	}
	return o.VcsStartTime, true
}

// HasVcsStartTime returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsStartTime() bool {
	if o != nil && !IsNil(o.VcsStartTime) {
		return true
	}

	return false
}

// SetVcsStartTime gets a reference to the given string and assigns it to the VcsStartTime field.
func (o *CommonsLastJobProcessedMeta) SetVcsStartTime(v string) {
	o.VcsStartTime = &v
}

// GetVcsWorkflowGroupId returns the VcsWorkflowGroupId field value if set, zero value otherwise.
func (o *CommonsLastJobProcessedMeta) GetVcsWorkflowGroupId() string {
	if o == nil || IsNil(o.VcsWorkflowGroupId) {
		var ret string
		return ret
	}
	return *o.VcsWorkflowGroupId
}

// GetVcsWorkflowGroupIdOk returns a tuple with the VcsWorkflowGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsLastJobProcessedMeta) GetVcsWorkflowGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.VcsWorkflowGroupId) {
		return nil, false
	}
	return o.VcsWorkflowGroupId, true
}

// HasVcsWorkflowGroupId returns a boolean if a field has been set.
func (o *CommonsLastJobProcessedMeta) HasVcsWorkflowGroupId() bool {
	if o != nil && !IsNil(o.VcsWorkflowGroupId) {
		return true
	}

	return false
}

// SetVcsWorkflowGroupId gets a reference to the given string and assigns it to the VcsWorkflowGroupId field.
func (o *CommonsLastJobProcessedMeta) SetVcsWorkflowGroupId(v string) {
	o.VcsWorkflowGroupId = &v
}

func (o CommonsLastJobProcessedMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsLastJobProcessedMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VcsBaseRef) {
		toSerialize["vcs_base_ref"] = o.VcsBaseRef
	}
	if !IsNil(o.VcsCommitMessage) {
		toSerialize["vcs_commit_message"] = o.VcsCommitMessage
	}
	if !IsNil(o.VcsDefaultBranch) {
		toSerialize["vcs_default_branch"] = o.VcsDefaultBranch
	}
	if !IsNil(o.VcsEndTime) {
		toSerialize["vcs_end_time"] = o.VcsEndTime
	}
	if !IsNil(o.VcsHeadRef) {
		toSerialize["vcs_head_ref"] = o.VcsHeadRef
	}
	if !IsNil(o.VcsJobName) {
		toSerialize["vcs_job_name"] = o.VcsJobName
	}
	if !IsNil(o.VcsOrg) {
		toSerialize["vcs_org"] = o.VcsOrg
	}
	if !IsNil(o.VcsRef) {
		toSerialize["vcs_ref"] = o.VcsRef
	}
	if !IsNil(o.VcsRefType) {
		toSerialize["vcs_ref_type"] = o.VcsRefType
	}
	if !IsNil(o.VcsRepo) {
		toSerialize["vcs_repo"] = o.VcsRepo
	}
	if !IsNil(o.VcsStartTime) {
		toSerialize["vcs_start_time"] = o.VcsStartTime
	}
	if !IsNil(o.VcsWorkflowGroupId) {
		toSerialize["vcs_workflow_group_id"] = o.VcsWorkflowGroupId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsLastJobProcessedMeta) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsLastJobProcessedMeta := _CommonsLastJobProcessedMeta{}

	err = json.Unmarshal(bytes, &varCommonsLastJobProcessedMeta)

	if err != nil {
		return err
	}

	*o = CommonsLastJobProcessedMeta(varCommonsLastJobProcessedMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "vcs_base_ref")
		delete(additionalProperties, "vcs_commit_message")
		delete(additionalProperties, "vcs_default_branch")
		delete(additionalProperties, "vcs_end_time")
		delete(additionalProperties, "vcs_head_ref")
		delete(additionalProperties, "vcs_job_name")
		delete(additionalProperties, "vcs_org")
		delete(additionalProperties, "vcs_ref")
		delete(additionalProperties, "vcs_ref_type")
		delete(additionalProperties, "vcs_repo")
		delete(additionalProperties, "vcs_start_time")
		delete(additionalProperties, "vcs_workflow_group_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsLastJobProcessedMeta struct {
	value *CommonsLastJobProcessedMeta
	isSet bool
}

func (v NullableCommonsLastJobProcessedMeta) Get() *CommonsLastJobProcessedMeta {
	return v.value
}

func (v *NullableCommonsLastJobProcessedMeta) Set(val *CommonsLastJobProcessedMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsLastJobProcessedMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsLastJobProcessedMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsLastJobProcessedMeta(val *CommonsLastJobProcessedMeta) *NullableCommonsLastJobProcessedMeta {
	return &NullableCommonsLastJobProcessedMeta{value: val, isSet: true}
}

func (v NullableCommonsLastJobProcessedMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsLastJobProcessedMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


