/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsReqSetupIntentInit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsReqSetupIntentInit{}

// CommonsReqSetupIntentInit struct for CommonsReqSetupIntentInit
type CommonsReqSetupIntentInit struct {
	CancelUrl string `json:"cancel_url"`
	SuccessUrl string `json:"success_url"`
	AdditionalProperties map[string]interface{}
}

type _CommonsReqSetupIntentInit CommonsReqSetupIntentInit

// NewCommonsReqSetupIntentInit instantiates a new CommonsReqSetupIntentInit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsReqSetupIntentInit(cancelUrl string, successUrl string) *CommonsReqSetupIntentInit {
	this := CommonsReqSetupIntentInit{}
	this.CancelUrl = cancelUrl
	this.SuccessUrl = successUrl
	return &this
}

// NewCommonsReqSetupIntentInitWithDefaults instantiates a new CommonsReqSetupIntentInit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsReqSetupIntentInitWithDefaults() *CommonsReqSetupIntentInit {
	this := CommonsReqSetupIntentInit{}
	return &this
}

// GetCancelUrl returns the CancelUrl field value
func (o *CommonsReqSetupIntentInit) GetCancelUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value
// and a boolean to check if the value has been set.
func (o *CommonsReqSetupIntentInit) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelUrl, true
}

// SetCancelUrl sets field value
func (o *CommonsReqSetupIntentInit) SetCancelUrl(v string) {
	o.CancelUrl = v
}

// GetSuccessUrl returns the SuccessUrl field value
func (o *CommonsReqSetupIntentInit) GetSuccessUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuccessUrl
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value
// and a boolean to check if the value has been set.
func (o *CommonsReqSetupIntentInit) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessUrl, true
}

// SetSuccessUrl sets field value
func (o *CommonsReqSetupIntentInit) SetSuccessUrl(v string) {
	o.SuccessUrl = v
}

func (o CommonsReqSetupIntentInit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsReqSetupIntentInit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cancel_url"] = o.CancelUrl
	toSerialize["success_url"] = o.SuccessUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsReqSetupIntentInit) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsReqSetupIntentInit := _CommonsReqSetupIntentInit{}

	if err = json.Unmarshal(bytes, &varCommonsReqSetupIntentInit); err == nil {
		*o = CommonsReqSetupIntentInit(varCommonsReqSetupIntentInit)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "cancel_url")
		delete(additionalProperties, "success_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsReqSetupIntentInit struct {
	value *CommonsReqSetupIntentInit
	isSet bool
}

func (v NullableCommonsReqSetupIntentInit) Get() *CommonsReqSetupIntentInit {
	return v.value
}

func (v *NullableCommonsReqSetupIntentInit) Set(val *CommonsReqSetupIntentInit) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsReqSetupIntentInit) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsReqSetupIntentInit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsReqSetupIntentInit(val *CommonsReqSetupIntentInit) *NullableCommonsReqSetupIntentInit {
	return &NullableCommonsReqSetupIntentInit{value: val, isSet: true}
}

func (v NullableCommonsReqSetupIntentInit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsReqSetupIntentInit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


