/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsOrganization{}

// CommonsOrganization struct for CommonsOrganization
type CommonsOrganization struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	CreatedBy *int32 `json:"created_by,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsOrganization CommonsOrganization

// NewCommonsOrganization instantiates a new CommonsOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsOrganization() *CommonsOrganization {
	this := CommonsOrganization{}
	return &this
}

// NewCommonsOrganizationWithDefaults instantiates a new CommonsOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsOrganizationWithDefaults() *CommonsOrganization {
	this := CommonsOrganization{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *CommonsOrganization) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrganization) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *CommonsOrganization) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *CommonsOrganization) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *CommonsOrganization) GetCreatedBy() int32 {
	if o == nil || IsNil(o.CreatedBy) {
		var ret int32
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrganization) GetCreatedByOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *CommonsOrganization) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given int32 and assigns it to the CreatedBy field.
func (o *CommonsOrganization) SetCreatedBy(v int32) {
	o.CreatedBy = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CommonsOrganization) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrganization) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CommonsOrganization) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CommonsOrganization) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CommonsOrganization) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrganization) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CommonsOrganization) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CommonsOrganization) SetName(v string) {
	o.Name = &v
}

func (o CommonsOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsOrganization) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsOrganization := _CommonsOrganization{}

<<<<<<< HEAD
	err = json.Unmarshal(bytes, &varCommonsOrganization)

	if err != nil {
		return err
	}

	*o = CommonsOrganization(varCommonsOrganization)

=======
	if err = json.Unmarshal(bytes, &varCommonsOrganization); err == nil {
		*o = CommonsOrganization(varCommonsOrganization)
	}

>>>>>>> prajjwal-warp-323
	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "avatar_url")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsOrganization struct {
	value *CommonsOrganization
	isSet bool
}

func (v NullableCommonsOrganization) Get() *CommonsOrganization {
	return v.value
}

func (v *NullableCommonsOrganization) Set(val *CommonsOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsOrganization(val *CommonsOrganization) *NullableCommonsOrganization {
	return &NullableCommonsOrganization{value: val, isSet: true}
}

func (v NullableCommonsOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


