/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package warpbuild

import (
	"encoding/json"
)

// checks if the CommonsUpdateRunnerInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsUpdateRunnerInput{}

// CommonsUpdateRunnerInput struct for CommonsUpdateRunnerInput
type CommonsUpdateRunnerInput struct {
	Active *bool `json:"Active,omitempty"`
<<<<<<< HEAD
	Configuration *CommonsRunnerConfiguration `json:"configuration,omitempty"`
	Labels map[string]interface{} `json:"labels,omitempty"`
=======
	Configuration *CommonsRunnerSetConfiguration `json:"configuration,omitempty"`
	Labels []string `json:"labels,omitempty"`
	Name *string `json:"name,omitempty"`
>>>>>>> prajjwal-warp-323
	AdditionalProperties map[string]interface{}
}

type _CommonsUpdateRunnerInput CommonsUpdateRunnerInput

// NewCommonsUpdateRunnerInput instantiates a new CommonsUpdateRunnerInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsUpdateRunnerInput() *CommonsUpdateRunnerInput {
	this := CommonsUpdateRunnerInput{}
	return &this
}

// NewCommonsUpdateRunnerInputWithDefaults instantiates a new CommonsUpdateRunnerInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsUpdateRunnerInputWithDefaults() *CommonsUpdateRunnerInput {
	this := CommonsUpdateRunnerInput{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CommonsUpdateRunnerInput) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsUpdateRunnerInput) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CommonsUpdateRunnerInput) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CommonsUpdateRunnerInput) SetActive(v bool) {
	o.Active = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
<<<<<<< HEAD
func (o *CommonsUpdateRunnerInput) GetConfiguration() CommonsRunnerConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret CommonsRunnerConfiguration
=======
func (o *CommonsUpdateRunnerInput) GetConfiguration() CommonsRunnerSetConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret CommonsRunnerSetConfiguration
>>>>>>> prajjwal-warp-323
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
<<<<<<< HEAD
func (o *CommonsUpdateRunnerInput) GetConfigurationOk() (*CommonsRunnerConfiguration, bool) {
=======
func (o *CommonsUpdateRunnerInput) GetConfigurationOk() (*CommonsRunnerSetConfiguration, bool) {
>>>>>>> prajjwal-warp-323
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *CommonsUpdateRunnerInput) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

<<<<<<< HEAD
// SetConfiguration gets a reference to the given CommonsRunnerConfiguration and assigns it to the Configuration field.
func (o *CommonsUpdateRunnerInput) SetConfiguration(v CommonsRunnerConfiguration) {
=======
// SetConfiguration gets a reference to the given CommonsRunnerSetConfiguration and assigns it to the Configuration field.
func (o *CommonsUpdateRunnerInput) SetConfiguration(v CommonsRunnerSetConfiguration) {
>>>>>>> prajjwal-warp-323
	o.Configuration = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
<<<<<<< HEAD
func (o *CommonsUpdateRunnerInput) GetLabels() map[string]interface{} {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]interface{}
=======
func (o *CommonsUpdateRunnerInput) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
>>>>>>> prajjwal-warp-323
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
<<<<<<< HEAD
func (o *CommonsUpdateRunnerInput) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]interface{}{}, false
=======
func (o *CommonsUpdateRunnerInput) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
>>>>>>> prajjwal-warp-323
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CommonsUpdateRunnerInput) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

<<<<<<< HEAD
// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *CommonsUpdateRunnerInput) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

=======
// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *CommonsUpdateRunnerInput) SetLabels(v []string) {
	o.Labels = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CommonsUpdateRunnerInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsUpdateRunnerInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CommonsUpdateRunnerInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CommonsUpdateRunnerInput) SetName(v string) {
	o.Name = &v
}

>>>>>>> prajjwal-warp-323
func (o CommonsUpdateRunnerInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsUpdateRunnerInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["Active"] = o.Active
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
<<<<<<< HEAD
=======
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
>>>>>>> prajjwal-warp-323

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsUpdateRunnerInput) UnmarshalJSON(bytes []byte) (err error) {
	varCommonsUpdateRunnerInput := _CommonsUpdateRunnerInput{}

<<<<<<< HEAD
	err = json.Unmarshal(bytes, &varCommonsUpdateRunnerInput)

	if err != nil {
		return err
	}

	*o = CommonsUpdateRunnerInput(varCommonsUpdateRunnerInput)

=======
	if err = json.Unmarshal(bytes, &varCommonsUpdateRunnerInput); err == nil {
		*o = CommonsUpdateRunnerInput(varCommonsUpdateRunnerInput)
	}

>>>>>>> prajjwal-warp-323
	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "Active")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "labels")
<<<<<<< HEAD
=======
		delete(additionalProperties, "name")
>>>>>>> prajjwal-warp-323
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsUpdateRunnerInput struct {
	value *CommonsUpdateRunnerInput
	isSet bool
}

func (v NullableCommonsUpdateRunnerInput) Get() *CommonsUpdateRunnerInput {
	return v.value
}

func (v *NullableCommonsUpdateRunnerInput) Set(val *CommonsUpdateRunnerInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsUpdateRunnerInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsUpdateRunnerInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsUpdateRunnerInput(val *CommonsUpdateRunnerInput) *NullableCommonsUpdateRunnerInput {
	return &NullableCommonsUpdateRunnerInput{value: val, isSet: true}
}

func (v NullableCommonsUpdateRunnerInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsUpdateRunnerInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


