name: Branch Build and Upload to R2

on:
  push:
    branches:
      - "obs"
      - "update-deps"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.WB_PACKAGES_DEV_R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.WB_PACKAGES_DEV_R2_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: warpbuild-packages-dev
  AWS_S3_REGION: us-east-1
  AWS_S3_BUCKET_HOST: https://bcfda61174f1fa286a9ecf6b2dde0c49.r2.cloudflarestorage.com

jobs:
  build-and-upload:
    runs-on: warp-ubuntu-latest-x64-16x

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: WarpBuilds/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Define S3 Path
        id: vars
        run: echo "s3_path=warpbuild-agentd/${GITHUB_REF_NAME}/" >> $GITHUB_ENV

      - name: Run GoReleaser (Snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List all dist files
        run: ls -l dist

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for Cloudflare R2
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [r2]
          type            = s3
          provider        = Cloudflare
          env_auth        = false
          access_key_id   = ${AWS_ACCESS_KEY_ID}
          secret_access_key = ${AWS_SECRET_ACCESS_KEY}
          endpoint        = ${AWS_S3_BUCKET_HOST}
          region          = ${AWS_S3_REGION}
          acl             = private
          EOF

      - name: Sync to R2 with rclone
        run: |
          rclone sync dist r2:${AWS_S3_BUCKET}/${{ env.s3_path }} --progress
