name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race ./...
